services:
  postgresql:
    image: postgres:16.4
    container_name: postgresql
    ports: ["5432:5432"]
    volumes:
      - ./tmp/postgresql/data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=SpringBootDemo
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 10
    networks: ["springbootdemo"]
networks:
  springbootdemo:
    external: true